### ISSUE TITLE
Theme-Übersicht

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FakThemesDoku#1]
Wir brauchen eine Übersichtsseite, auf der jedes Theme mit seinem Screenshot sichtbar und kurz erläutert ist.

**Comment by AstridSemm** [comment]
Fehlt da noch etwas oder kann man das lassen?
https://www.wordpress.rrze.fau.de/allgemeines/uebersicht-ueber-die-themes-der-fakultaeten/

**Comment by wrkb** [comment]
…spontan sieht es gut aus ☺
Es fehlt vielleicht noch die Suchfunktion oben und die Metanavigation unten beinhaltet doch streng genommen nicht das Logo und die Adresse – wird auch nicht gemeinsam gepflegt. Würde den Rahmen nur ums Menü legen und den Adressbereich separat benennen.

Grüße

Karsten

Webredaktion fau.de/fau.eu
09131/85-70203

Wichtig: Bitte senden Sie Anliegen zu Webseiten immer an die gesamte Webredaktion via webredaktion@fau.de<mailto:webredaktion@fau.de>. Sonst kann es zu Verzögerungen kommen.

Von: Astrid [mailto:notifications@github.com]
Gesendet: Montag, 21. Dezember 2015 14:42
An: RRZE-Webteam/FakThemesDoku
Betreff: Re: [FakThemesDoku] Theme-Übersicht (#1)


Fehlt da noch etwas oder kann man das lassen?
https://www.wordpress.rrze.fau.de/allgemeines/uebersicht-ueber-die-themes-der-fakultaeten/

**Comment by AstridSemm** [comment]
ToDo: Unterseiten für jedes Theme mit ein bis zwei Screenshots und Kurzbeschreibung

**Comment by AstridSemm** [comment]
So, dann wären jetzt auch ein paar Bildergalerien mit Screenshots da: https://www.wordpress.rrze.fau.de/allgemeines/uebersicht-ueber-die-themes-der-fakultaeten/bildergalerien/
