### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FakThemesDoku#2]
Wir brauchen verschiedene "Fragen & Antworten"-Seiten für die Themengebiete.

ggf. überlegen, mit was für ein Plugin man das machen kann, ob wir das selbst machen oder was übernehmen oder OTRS einbinden können

**Comment by AstridSemm** [comment]
Ich würde das über ein Glossar machen - hübsch übersichtlich und alphabetisch geordnet. Beispiel hier: https://www.wordpress.rrze.fau.de/allgemeines/glossar/
Sind die Fragen, die aufgenommen werden sollen, im OTRS getaggt oder darf ich da jetzt filzen gehen?

**Comment by wrkb** [comment]
Ketzerische Frage angesichts der investierten Mühe, aber konstruktiv gemeint: Werden solche FAQ wirklich frequentiert? Wer mit dem CMS arbeitet, der trifft doch seltener auf Stichworte, sondern eher auf die Box oder die Funktion unter seiner Maus. Wenn ich etwa die Boxen Schlagworte und Kategorie sehe, dann würde ich nicht in einem Glossar (der einen Überblick ohne Kontext bietet) schauen, sondern auf https://www.wordpress.rrze.fau.de/redaktion/seiten/eine-seite-erstellen/ und dort einen Hinweis auf die Funktion erwarten (falls die Kontexthilfe im Backend nicht reicht). Auf der Seite wäre ein Link zu einer Erklärung von Taxonomie hilfreicher m.E. Haben Nutzer im Arbeitsalltag wirklich Zeit, Glossare zu lesen, wo doch schon aussagekräftige Handbücher nur von einem Teil der Nutzer genutzt werden?

Schönen Gruß!

**Comment by AstridSemm** [comment]
Ich weiß es nicht, Karsten. Man kann's auch mit einem "einfachen" Accordion lösen (was einen ähnlichen Aufwand zur Folge hat) oder ganz anders. Nutzer sind meistens ganz dankbar, wenn sie eine Zusammenstellung der häufigsten Fragen haben als eine Art Schnellzugriff, ja.

**Comment by xwolfde** [comment]
Accordion haben den Vorteil, dass du dort Grafiken einbinden kannst etc. pp. UND: Mit der neuen version hast du bei FAU-Einrichtungen- und en Fakultäten-Themes dann auch die Verlinkung der Accordions. Das ist bei Glossar (noch) nicht der Fall.

**Comment by AstridSemm** [comment]
Ok, Accordion. Wolfgang, das beantwortet die andere Frage nicht: Sind die Sachen im OTRS getaggt?

**Comment by wrkb** [comment]
Achso, nein, ich meinte den Aufwand für die speziell diese Zusammenstellung anstatt im Handbuch. Nicht das Werkzeug. Sprich: Bevor ich zum Glossar/Akkordion/wasauchimmer gesprungen bin und das betreffende Wort gesucht habe, bin ich auch im Handbuch. Bzw. kann man Glossare (es sind ja keine Fragen, nur Stichworte) nicht wirklich "lesen".

Aber ihr kennt eure Nutzer besser, es war nur ein Gedanke aus eigener Erfahrung und der in unserem Arbeitsbereich. Aber nachdem nun auch die Links auf Akkordion-Einträge möglich sind, ist das alles vielleicht hinfällig, dann kannst du aus dem Handbuch heraus auf die Einträge springen.

**Comment by AstridSemm** [comment]
Die FAQ kommen in das Handbuch...

**Comment by xwolfde** [comment]
OTRS-Getaggt? Nein.  Wenn, dann würden wir ja gleich das FAQ vom OTRS nehmen ... Wollen wir das? ^^

**Comment by AstridSemm** [comment]
Erledigt - zumindest vorläufig. Wenn noch jemand weitere FAQs hat, kann ich die gern einarbeiten. 
https://www.wordpress.rrze.fau.de/haeufig-gestellte-fragen/
