### ISSUE TITLE
Tipp: Lightboxes bei Bildern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FakThemesDoku#3]
Bilder, die via Galery eingefügt werden haben bereits dei schöne Funktion, daß bei einem Klick auf diese das Bild in einer Art Popup dargestellt wird.
Dies ist auch bei Bildenr möglich, die man manuell in dem Artikel einfügt.
Hierzu ist folgendes zu tun: Das Bild wird mit der Mediendatei verlinkt.
Unter den erweiterten Bildeinstellungen wird dann im Eingabefeld "CSS-Klasse verknüpfen" die Angabe "lightbox" eingefügt.

**Comment by AstridSemm** [comment]
Gehe ich recht in der Annahme, dass ich da einen Tipp-Beitrag schreiben soll?

**Comment by xwolfde** [comment]
Das wäre ein Vorschlag :+1:
